### PR TITLE
Release 3.6.1

### PR DESCRIPTION
**Pull request by rprouse**
These are the changes to this project to produce the 3.6.1 hotfix. I had to update the Cake build scripts to get it to build on my machine. The MSI has been uploaded to the release in the console project and archived on nunit.org.

This can be merged after review.

### CODE REVIEW

**Comment by CharliePoole** [comment]
@ChrisMaddock is familiar with this and I'm not. 😞

**Comment by ChrisMaddock** [comment]
My phone won't let me line comment, but this reverts the changes on line 13-14 of build.ps1, which were necessary to build last time around.

The Cake.ExtendedNuGet package has caused all sorts of dependency issues...I thought we finally had all the plates spinning at once. 😞 I'd like to pull this down and try it before merging, to make sure this works in both cases - I'll try and get round to that this weekend.

Sorry for all the problems, Rob.

**Comment by CharliePoole** [comment]
Do we have a common understanding of what we modify and don't modify wrt Cake? For most projects, I've been assuming that Cake itself, Nuget, build.ps1 and build can be updated at any time, so only the packages.config in the tools directory is part of our maintained code. Is that what you guys are thinking as well?

@ChrisMaddock It seems like you were forced to modify build.ps1 to get things to work. In that case, maybe the script needs a comment to say so, something that would have jumped out clearly in the diff.
We should come to an understanding and then - in case any project needs to do something different - we can add comments for future maintainers.

After writing the above, I'm now wondering if we should remove the two cake-provided build scripts from our repositories for most projects.

**Comment by ChrisMaddock** [comment]
>  It seems like you were forced to modify build.ps1 to get things to work. In that case, maybe the script needs a comment to say so, something that would have jumped out clearly in the diff.

Sure. The change was commented, but it should probably have been highlighted more obviously at the top of the file. 

I believe the common approach for the `build.*` scripts is to copy the Cake supplied ones as a template, and then modify as required. Here, I made the change needed in the bootstrapper with this idea. Unfortunately, due to several bugs over time, we've got into the habit of just wholesale replacing the `build.*` scripts. (I've done the same in other repos.) Maybe we should get out of that habit.

All this said - if this is what worked for Rob, then sounds like my bootstrapper change may no longer be required, in which case, 'reverting the hack' is probably a good move!

> I'm now wondering if we should remove the two cake-provided build scripts from our repositories for most projects.

I'm not keen on this approach, this would make the user need to work harder to initially build the project.

**Comment by CharliePoole** [comment]
I've definitely been following the rule of deleting the cake scripts and letting them re-install when any problem arises. Our CI doesn't do that because the scripts are already present.

But anyway, all I'm saying is we should know what we are doing and do it in common for most projects, documenting differences. This discussion let me see that we are not all doing it the same way, which is OK but the different approaches need to be transparent.

**Comment by rprouse** [comment]
To get it to work on my machine, I cleared the nuget.exe and packages in the tools directory, got the latest version of build.ps1 from Cake and changed the NuGet.Core version in the build script. Once I did that, I was able to fetch packages and build the installer.

**Comment by ChrisMaddock** [comment]
There's been a new release of Cake.ExtendedNuGet - which used a different version of NuGet.Core to the one we had pinned. I don't have time to look at this properly before the next console release, so just pinned Cake.ExtendedNuGet to the old version as well. https://github.com/Redth/Cake.ExtendedNuGet/issues/7 is still open, so I don't expect the root issue is fixed yet.

**Pull request merged**
