### PR TITLE
Incremented the version to 3.6

### PR DESCRIPTION
**Pull request by rprouse**
Post 3.5 release.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Looks good.

Two questions:
1. Are we keeping the release branches here? 
2. Have you done anything with the msi yet? CHANGES.TXT still needs to be updated for 3.5 - partly the TC version change (my bad) - and a date.

On a wider note, do we want a CHANGES.TXT here? From memory, @CharliePoole - you were keen on this - could we just rely on the GitHub release notes here however, given they'll be so simple? 

@rprouse - just to note, the manual changes required for a release are listed at the bottom of the readme. Apologies, it would have been more helpful if I'd pointed that out earlier. 😄

**Comment by ChrisMaddock** [comment]
And 3. Would it be sensible to have CI required on this repo? I set it up, and obviously missed the checkbox, but can't access the settings to fix it I'm afraid!

**Comment by rprouse** [comment]
Ah, yes, I missed the `Changes.txt` 😦 I've uploaded the MSI to the console release, but I could redo it. I didn't realize we are maintaining one for this repo. Looking at it, it doesn't appear to be that useful. We should review after the release.

I will pull your PR and redo the release. Thanks for updating it.

**Comment by rprouse** [comment]
@ChrisMaddock good point. I have protected master in this repo.

**Pull request merged**
