### PR TITLE
Replace CHANGES.txt with autogenerated COMPONENTS.txt

### LINKED ISSUE #10: Better solution for Changes.txt
With the 3.5 release, the changes.txt file wasn't updated at first, and the question came up as to whether that was even a useful file to have.

I suggest we scrap it, it's too error prone. If we think there's a use for having a text contents, we could autogenerate something, showing the package versions included?

Alternatively, if we want to keep it, we should automate it.

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #10.

This generates a text file with each build, which lists the components included in the installer/zip. The generated file looks like this:

```
This package contains the following components:
NUnit.ConsoleRunner - 3.5.0
NUnit.Extension.NUnitProjectLoader - 3.5.0
NUnit.Extension.NUnitV2Driver - 3.5.0
NUnit.Extension.NUnitV2ResultWriter - 3.5.0
NUnit.Extension.TeamCityEventListener - 1.0.2
NUnit.Extension.VSProjectLoader - 3.5.0
```

What do we think?

### CODE REVIEW

**Comment by rprouse** [comment]
I'm good with this. @CharliePoole what do you think?

**Comment by CharliePoole** [comment]
Can you also fetch the description of what each component does and add it to the file?

**Comment by CharliePoole** [comment]
I'm good with this with or without the suggested addition but I think it would add a lot of value.

**Comment by ChrisMaddock** [comment]
I think so.

It currently uses the Cake.ExtendedNuGet addin, which only implements Name/Version - but given the NuGet Core package has to be referenced anyway, it should be possible just to use that directly. It's only a couple of lines - will try it tomorrow. 😄

**Comment by ChrisMaddock** [comment]
All good, the file now looks like this:
```
This package contains the following components:

NUnit.ConsoleRunner - 3.5.0
Console runner for the NUnit 3 unit-testing framework, without any extensions.

NUnit.Extension.NUnitProjectLoader - 3.5.0
NUnit Engine extension for loading NUnit projects.

NUnit.Extension.NUnitV2Driver - 3.5.0
NUnit Engine extension allowing execution of tests using NUnit 2.x.

NUnit.Extension.NUnitV2ResultWriter - 3.5.0
NUnit Engine extension for writing test result files in NUnit V2 format.

NUnit.Extension.TeamCityEventListener - 1.0.2
NUnit Team City Event Listener extension for TeamCity.

NUnit.Extension.VSProjectLoader - 3.5.0
NUnit Engine extension for loading Visual Studio formatted projects.
```

**Comment by CharliePoole** [comment]
Cool!

**Pull request merged**
